# Generated by Django 2.0.2 on 2018-07-05 20:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('domain', models.CharField(choices=[('IT', 'Technology'), ('BIZ', 'Business'), ('SP', 'Sports'), ('EN', 'Entertainment'), ('POL', 'Politics')], default='POL', max_length=3)),
                ('slug', models.SlugField(allow_unicode=True, unique=True)),
                ('image', models.ImageField(upload_to='image/')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('hunter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
